### ISSUE TITLE
https://www.ssrgeek.com/home Route is not working

### ISSUE THREAD

**Issue by yeasir99** [mdsaddamvol/ssrgeek-saddam#1]
when user click your brand logo (ssrgreek) it show page not found which is bad user experience so fix this issue.

**Comment by mdsaddamvol** [comment]
It’s still under development. Did not finalised yet.you will able to notice
if you go to bottom of the page. Thank you for visiting. More pages are
coming soon.

**Comment by yeasir99** [comment]
yeah i checked it. it's look pretty good. one another think is after clicking brand logo (ssrgreek) your navbar links not connect with proper path. by the way as you say it's still under development i hope it will be fixed. thank you bro
